/**
 * Catálogo central de permissões (`modulo:acao`). Usado tanto pelo backend
 * (guards, seed de Role/Permission) quanto pelo frontend (esconder/mostrar UI).
 * Módulos além destes são adicionados nas fases seguintes.
 */
export const PERMISSIONS = {
  USERS_VIEW: "users:view",
  USERS_CREATE: "users:create",
  USERS_EDIT: "users:edit",
  USERS_DELETE: "users:delete",

  ROLES_VIEW: "roles:view",
  ROLES_MANAGE: "roles:manage",

  COMPANY_VIEW: "company:view",
  COMPANY_MANAGE: "company:manage",

  DASHBOARD_VIEW: "dashboard:view",

  PROPERTIES_VIEW: "properties:view",
  PROPERTIES_CREATE: "properties:create",
  PROPERTIES_EDIT: "properties:edit",
  PROPERTIES_DELETE: "properties:delete",

  TAGS_VIEW: "tags:view",
  TAGS_MANAGE: "tags:manage",

  DUE_DILIGENCE_VIEW: "due_diligence:view",
  DUE_DILIGENCE_MANAGE: "due_diligence:manage",

  ACQUISITION_VIEW: "acquisition:view",
  ACQUISITION_MANAGE: "acquisition:manage",

  LEGAL_VIEW: "legal:view",
  LEGAL_MANAGE: "legal:manage",

  RENOVATION_VIEW: "renovation:view",
  RENOVATION_MANAGE: "renovation:manage",

  FINANCE_VIEW: "finance:view",
  FINANCE_MANAGE: "finance:manage",

  SIMULATOR_VIEW: "simulator:view",
  SIMULATOR_MANAGE: "simulator:manage",

  INVESTORS_VIEW: "investors:view",
  INVESTORS_MANAGE: "investors:manage",

  SALES_VIEW: "sales:view",
  SALES_MANAGE: "sales:manage",

  REPORTS_VIEW: "reports:view",
  REPORTS_MANAGE: "reports:manage",
} as const;

export type PermissionKey = keyof typeof PERMISSIONS;
export type PermissionValue = (typeof PERMISSIONS)[PermissionKey];

export const DEFAULT_ROLES = [
  "ADMINISTRADOR",
  "SOCIO",
  "DIRETOR",
  "GERENTE",
  "JURIDICO",
  "ENGENHARIA",
  "FINANCEIRO",
  "CORRETOR",
  "INVESTIDOR",
  "VISITANTE",
] as const;

export type DefaultRoleName = (typeof DEFAULT_ROLES)[number];

/** Permissões concedidas a cada papel-base no seed inicial. */
export const DEFAULT_ROLE_PERMISSIONS: Record<DefaultRoleName, PermissionValue[]> = {
  ADMINISTRADOR: Object.values(PERMISSIONS),
  SOCIO: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.COMPANY_VIEW,
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.PROPERTIES_VIEW,
    PERMISSIONS.TAGS_VIEW,
    PERMISSIONS.DUE_DILIGENCE_VIEW,
    PERMISSIONS.ACQUISITION_VIEW,
    PERMISSIONS.LEGAL_VIEW,
    PERMISSIONS.RENOVATION_VIEW,
    PERMISSIONS.FINANCE_VIEW,
    PERMISSIONS.SIMULATOR_VIEW,
    PERMISSIONS.INVESTORS_VIEW,
    PERMISSIONS.SALES_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_MANAGE,
  ],
  DIRETOR: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.COMPANY_VIEW,
    PERMISSIONS.PROPERTIES_VIEW,
    PERMISSIONS.TAGS_VIEW,
    PERMISSIONS.DUE_DILIGENCE_VIEW,
    PERMISSIONS.ACQUISITION_VIEW,
    PERMISSIONS.LEGAL_VIEW,
    PERMISSIONS.RENOVATION_VIEW,
    PERMISSIONS.FINANCE_VIEW,
    PERMISSIONS.SIMULATOR_VIEW,
    PERMISSIONS.INVESTORS_VIEW,
    PERMISSIONS.SALES_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_MANAGE,
  ],
  GERENTE: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.PROPERTIES_VIEW,
    PERMISSIONS.PROPERTIES_CREATE,
    PERMISSIONS.PROPERTIES_EDIT,
    PERMISSIONS.PROPERTIES_DELETE,
    PERMISSIONS.TAGS_VIEW,
    PERMISSIONS.TAGS_MANAGE,
    PERMISSIONS.DUE_DILIGENCE_VIEW,
    PERMISSIONS.DUE_DILIGENCE_MANAGE,
    PERMISSIONS.ACQUISITION_VIEW,
    PERMISSIONS.ACQUISITION_MANAGE,
    PERMISSIONS.LEGAL_VIEW,
    PERMISSIONS.LEGAL_MANAGE,
    PERMISSIONS.RENOVATION_VIEW,
    PERMISSIONS.RENOVATION_MANAGE,
    PERMISSIONS.FINANCE_VIEW,
    PERMISSIONS.SIMULATOR_VIEW,
    PERMISSIONS.SIMULATOR_MANAGE,
    PERMISSIONS.INVESTORS_VIEW,
    PERMISSIONS.SALES_VIEW,
    PERMISSIONS.SALES_MANAGE,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_MANAGE,
  ],
  JURIDICO: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.PROPERTIES_VIEW,
    PERMISSIONS.TAGS_VIEW,
    PERMISSIONS.DUE_DILIGENCE_VIEW,
    PERMISSIONS.DUE_DILIGENCE_MANAGE,
    PERMISSIONS.ACQUISITION_VIEW,
    PERMISSIONS.LEGAL_VIEW,
    PERMISSIONS.LEGAL_MANAGE,
  ],
  ENGENHARIA: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.PROPERTIES_VIEW,
    PERMISSIONS.TAGS_VIEW,
    PERMISSIONS.DUE_DILIGENCE_VIEW,
    PERMISSIONS.RENOVATION_VIEW,
    PERMISSIONS.RENOVATION_MANAGE,
  ],
  FINANCEIRO: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.PROPERTIES_VIEW,
    PERMISSIONS.TAGS_VIEW,
    PERMISSIONS.DUE_DILIGENCE_VIEW,
    PERMISSIONS.ACQUISITION_VIEW,
    PERMISSIONS.ACQUISITION_MANAGE,
    PERMISSIONS.LEGAL_VIEW,
    PERMISSIONS.RENOVATION_VIEW,
    PERMISSIONS.FINANCE_VIEW,
    PERMISSIONS.FINANCE_MANAGE,
    PERMISSIONS.SIMULATOR_VIEW,
    PERMISSIONS.SIMULATOR_MANAGE,
    PERMISSIONS.INVESTORS_VIEW,
    PERMISSIONS.SALES_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_MANAGE,
  ],
  // Escopado por linha no service (PropertiesService/SalesService) via
  // User.brokerId: só enxerga/edita imóveis e vendas atribuídos a ele ou
  // cadastrados por ele — mesmo tendo as chaves de permissão "amplas" abaixo.
  CORRETOR: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.PROPERTIES_VIEW,
    PERMISSIONS.PROPERTIES_EDIT,
    PERMISSIONS.SALES_VIEW,
    PERMISSIONS.SALES_MANAGE,
  ],
  // Escopado por linha no service (InvestorsService/PropertiesService) via
  // User.investorId: só enxerga a própria participação/prestação de contas.
  // Sem finance:view/sales:view/dashboard:view — esses agregados somam a
  // empresa inteira e não têm escopo por investidor nesta entrega.
  INVESTIDOR: [PERMISSIONS.INVESTORS_VIEW, PERMISSIONS.PROPERTIES_VIEW],
  VISITANTE: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.PROPERTIES_VIEW,
    PERMISSIONS.TAGS_VIEW,
    PERMISSIONS.DUE_DILIGENCE_VIEW,
    PERMISSIONS.ACQUISITION_VIEW,
    PERMISSIONS.LEGAL_VIEW,
    PERMISSIONS.RENOVATION_VIEW,
    PERMISSIONS.FINANCE_VIEW,
    PERMISSIONS.SIMULATOR_VIEW,
    PERMISSIONS.INVESTORS_VIEW,
    PERMISSIONS.SALES_VIEW,
    PERMISSIONS.REPORTS_VIEW,
  ],
};
